# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:48:55+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Booking(BaseModel):
    BookingId: Optional[int] = None
    GameId: Optional[int] = None
    GameMinute: Optional[int] = None
    GameMinuteExtra: Optional[int] = None
    Name: Optional[str] = None
    PlayerId: Optional[int] = None
    TeamId: Optional[int] = None
    Type: Optional[str] = None


class Coach(BaseModel):
    CoachId: Optional[int] = None
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    Nationality: Optional[str] = None
    ShortName: Optional[str] = None


class DfsSlatePlayer(BaseModel):
    OperatorPlayerID: Optional[str] = None
    OperatorPlayerName: Optional[str] = None
    OperatorPosition: Optional[str] = None
    OperatorRosterSlots: Optional[List[str]] = None
    OperatorSalary: Optional[int] = None
    OperatorSlatePlayerID: Optional[str] = None
    PlayerGameProjectionStatID: Optional[int] = None
    PlayerID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None
    SlatePlayerID: Optional[int] = None
    Team: Optional[str] = None
    TeamID: Optional[int] = None


class Goal(BaseModel):
    AssistedByPlayerId1: Optional[int] = None
    AssistedByPlayerId2: Optional[int] = None
    AssistedByPlayerName1: Optional[str] = None
    AssistedByPlayerName2: Optional[str] = None
    GameId: Optional[int] = None
    GameMinute: Optional[int] = None
    GameMinuteExtra: Optional[int] = None
    GoalId: Optional[int] = None
    Name: Optional[str] = None
    PlayerId: Optional[int] = None
    TeamId: Optional[int] = None
    Type: Optional[str] = None


class Lineup(BaseModel):
    GameId: Optional[int] = None
    GameMinute: Optional[int] = None
    GameMinuteExtra: Optional[int] = None
    LineupId: Optional[int] = None
    Name: Optional[str] = None
    PitchPositionHorizontal: Optional[int] = None
    PitchPositionVertical: Optional[int] = None
    PlayerId: Optional[int] = None
    Position: Optional[str] = None
    ReplacedPlayerId: Optional[int] = None
    ReplacedPlayerName: Optional[str] = None
    TeamId: Optional[int] = None
    Type: Optional[str] = None


class Membership(BaseModel):
    Active: Optional[bool] = None
    EndDate: Optional[str] = None
    Jersey: Optional[int] = None
    MembershipId: Optional[int] = None
    PlayerId: Optional[int] = None
    PlayerName: Optional[str] = None
    StartDate: Optional[str] = None
    TeamArea: Optional[str] = None
    TeamId: Optional[int] = None
    TeamName: Optional[str] = None
    Updated: Optional[str] = None


class PenaltyShootout(BaseModel):
    GameId: Optional[int] = None
    Name: Optional[str] = None
    Order: Optional[int] = None
    PenaltyShootoutId: Optional[int] = None
    PlayerId: Optional[int] = None
    Position: Optional[str] = None
    TeamId: Optional[int] = None
    Type: Optional[str] = None


class Player(BaseModel):
    BirthCity: Optional[str] = None
    BirthCountry: Optional[str] = None
    BirthDate: Optional[str] = None
    CommonName: Optional[str] = None
    DraftKingsPosition: Optional[str] = None
    FirstName: Optional[str] = None
    Foot: Optional[str] = None
    Gender: Optional[str] = None
    Height: Optional[int] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Jersey: Optional[int] = None
    LastName: Optional[str] = None
    Nationality: Optional[str] = None
    PhotoUrl: Optional[str] = None
    PlayerId: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RotoWirePlayerID: Optional[int] = None
    ShortName: Optional[str] = None
    Updated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUpdated: Optional[str] = None
    UsaTodayHeadshotNoBackgroundUrl: Optional[str] = None
    UsaTodayHeadshotUpdated: Optional[str] = None
    UsaTodayHeadshotUrl: Optional[str] = None
    UsaTodayPlayerID: Optional[int] = None
    Weight: Optional[int] = None


class PlayerGame(BaseModel):
    Assists: Optional[float] = None
    BlockedShots: Optional[float] = None
    Captain: Optional[bool] = None
    CornersWon: Optional[float] = None
    Crosses: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefenderCleanSheets: Optional[float] = None
    DraftKingsPosition: Optional[str] = None
    DraftKingsSalary: Optional[int] = None
    FanDuelPosition: Optional[str] = None
    FanDuelSalary: Optional[int] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsMondogoal: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    Fouled: Optional[float] = None
    Fouls: Optional[float] = None
    GameId: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameId: Optional[int] = None
    GlobalOpponentId: Optional[int] = None
    GlobalTeamId: Optional[int] = None
    GoalkeeperCleanSheets: Optional[float] = None
    GoalkeeperGoalsAgainst: Optional[float] = None
    GoalkeeperSaves: Optional[float] = None
    GoalkeeperSingleGoalAgainst: Optional[float] = None
    GoalkeeperWins: Optional[float] = None
    Goals: Optional[float] = None
    HomeOrAway: Optional[str] = None
    InjuryBodyPart: Optional[str] = None
    InjuryNotes: Optional[str] = None
    InjuryStartDate: Optional[str] = None
    InjuryStatus: Optional[str] = None
    Interceptions: Optional[float] = None
    IsGameOver: Optional[bool] = None
    Jersey: Optional[int] = None
    LastManTackle: Optional[float] = None
    Minutes: Optional[float] = None
    MondogoalPosition: Optional[str] = None
    MondogoalSalary: Optional[int] = None
    Name: Optional[str] = None
    Offsides: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentId: Optional[int] = None
    OpponentScore: Optional[float] = None
    OwnGoals: Optional[float] = None
    Passes: Optional[float] = None
    PassesCompleted: Optional[float] = None
    PenaltiesConceded: Optional[float] = None
    PenaltiesWon: Optional[float] = None
    PenaltyKickGoals: Optional[float] = None
    PenaltyKickMisses: Optional[float] = None
    PenaltyKickSaves: Optional[float] = None
    PlayerId: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RedCards: Optional[float] = None
    RoundId: Optional[int] = None
    Score: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    ShortName: Optional[str] = None
    Shots: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    Started: Optional[int] = None
    StatId: Optional[int] = None
    Suspension: Optional[bool] = None
    SuspensionReason: Optional[str] = None
    Tackles: Optional[float] = None
    TacklesWon: Optional[float] = None
    Team: Optional[str] = None
    TeamId: Optional[int] = None
    Touches: Optional[float] = None
    Updated: Optional[str] = None
    UpdatedUtc: Optional[str] = None
    YahooPosition: Optional[str] = None
    YahooSalary: Optional[int] = None
    YellowCards: Optional[float] = None
    YellowRedCards: Optional[float] = None


class PlayerSeason(BaseModel):
    Assists: Optional[float] = None
    BlockedShots: Optional[float] = None
    CornersWon: Optional[float] = None
    Crosses: Optional[float] = None
    DefenderCleanSheets: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsMondogoal: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    Fouled: Optional[float] = None
    Fouls: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamId: Optional[int] = None
    GoalkeeperCleanSheets: Optional[float] = None
    GoalkeeperGoalsAgainst: Optional[float] = None
    GoalkeeperSaves: Optional[float] = None
    GoalkeeperSingleGoalAgainst: Optional[float] = None
    GoalkeeperWins: Optional[float] = None
    Goals: Optional[float] = None
    Interceptions: Optional[float] = None
    LastManTackle: Optional[float] = None
    Minutes: Optional[float] = None
    Name: Optional[str] = None
    Offsides: Optional[float] = None
    OpponentScore: Optional[float] = None
    OwnGoals: Optional[float] = None
    Passes: Optional[float] = None
    PassesCompleted: Optional[float] = None
    PenaltiesConceded: Optional[float] = None
    PenaltiesWon: Optional[float] = None
    PenaltyKickGoals: Optional[float] = None
    PenaltyKickMisses: Optional[float] = None
    PenaltyKickSaves: Optional[float] = None
    PlayerId: Optional[int] = None
    Position: Optional[str] = None
    PositionCategory: Optional[str] = None
    RedCards: Optional[float] = None
    RoundId: Optional[int] = None
    Score: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    ShortName: Optional[str] = None
    Shots: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    Started: Optional[int] = None
    StatId: Optional[int] = None
    Tackles: Optional[float] = None
    TacklesWon: Optional[float] = None
    Team: Optional[str] = None
    TeamId: Optional[int] = None
    Touches: Optional[float] = None
    Updated: Optional[str] = None
    UpdatedUtc: Optional[str] = None
    YellowCards: Optional[float] = None
    YellowRedCards: Optional[float] = None


class PlayoffAggregateScore(BaseModel):
    Created: Optional[str] = None
    TeamA_AggregateScore: Optional[int] = None
    TeamA_Id: Optional[int] = None
    TeamB_AggregateScore: Optional[int] = None
    TeamB_Id: Optional[int] = None
    Updated: Optional[str] = None
    WinningTeamId: Optional[int] = None


class Referee(BaseModel):
    FirstName: Optional[str] = None
    LastName: Optional[str] = None
    Nationality: Optional[str] = None
    RefereeId: Optional[int] = None
    ShortName: Optional[str] = None


class Standing(BaseModel):
    Draws: Optional[int] = None
    Games: Optional[int] = None
    GlobalTeamID: Optional[int] = None
    GoalsAgainst: Optional[int] = None
    GoalsDifferential: Optional[int] = None
    GoalsScored: Optional[int] = None
    Group: Optional[str] = None
    Losses: Optional[int] = None
    Name: Optional[str] = None
    Order: Optional[int] = None
    Points: Optional[int] = None
    RoundId: Optional[int] = None
    Scope: Optional[str] = None
    ShortName: Optional[str] = None
    StandingId: Optional[int] = None
    TeamId: Optional[int] = None
    Wins: Optional[int] = None


class Team(BaseModel):
    Active: Optional[bool] = None
    Address: Optional[str] = None
    AreaId: Optional[int] = None
    AreaName: Optional[str] = None
    City: Optional[str] = None
    ClubColor1: Optional[str] = None
    ClubColor2: Optional[str] = None
    ClubColor3: Optional[str] = None
    Email: Optional[str] = None
    Fax: Optional[str] = None
    Founded: Optional[int] = None
    FullName: Optional[str] = None
    Gender: Optional[str] = None
    GlobalTeamId: Optional[int] = None
    Key: Optional[str] = None
    Name: Optional[str] = None
    Nickname1: Optional[str] = None
    Nickname2: Optional[str] = None
    Nickname3: Optional[str] = None
    Phone: Optional[str] = None
    TeamId: Optional[int] = None
    Type: Optional[str] = None
    VenueId: Optional[int] = None
    VenueName: Optional[str] = None
    Website: Optional[str] = None
    WikipediaLogoUrl: Optional[str] = None
    WikipediaWordMarkUrl: Optional[str] = None
    Zip: Optional[str] = None


class TeamDetail(BaseModel):
    Active: Optional[bool] = None
    Address: Optional[str] = None
    AreaId: Optional[int] = None
    AreaName: Optional[str] = None
    City: Optional[str] = None
    ClubColor1: Optional[str] = None
    ClubColor2: Optional[str] = None
    ClubColor3: Optional[str] = None
    Email: Optional[str] = None
    Fax: Optional[str] = None
    Founded: Optional[int] = None
    FullName: Optional[str] = None
    Gender: Optional[str] = None
    GlobalTeamId: Optional[int] = None
    Key: Optional[str] = None
    Name: Optional[str] = None
    Nickname1: Optional[str] = None
    Nickname2: Optional[str] = None
    Nickname3: Optional[str] = None
    Phone: Optional[str] = None
    Players: Optional[List[Player]] = None
    TeamId: Optional[int] = None
    Type: Optional[str] = None
    VenueId: Optional[int] = None
    VenueName: Optional[str] = None
    Website: Optional[str] = None
    WikipediaLogoUrl: Optional[str] = None
    WikipediaWordMarkUrl: Optional[str] = None
    Zip: Optional[str] = None


class TeamGame(BaseModel):
    Assists: Optional[float] = None
    BlockedShots: Optional[float] = None
    CornersWon: Optional[float] = None
    Crosses: Optional[float] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DefenderCleanSheets: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsMondogoal: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    Fouled: Optional[float] = None
    Fouls: Optional[float] = None
    GameId: Optional[int] = None
    Games: Optional[int] = None
    GlobalGameId: Optional[int] = None
    GlobalOpponentId: Optional[int] = None
    GlobalTeamId: Optional[int] = None
    GoalkeeperCleanSheets: Optional[float] = None
    GoalkeeperGoalsAgainst: Optional[float] = None
    GoalkeeperSaves: Optional[float] = None
    GoalkeeperSingleGoalAgainst: Optional[float] = None
    GoalkeeperWins: Optional[float] = None
    Goals: Optional[float] = None
    HomeOrAway: Optional[str] = None
    Interceptions: Optional[float] = None
    IsGameOver: Optional[bool] = None
    LastManTackle: Optional[float] = None
    Minutes: Optional[float] = None
    Name: Optional[str] = None
    Offsides: Optional[float] = None
    Opponent: Optional[str] = None
    OpponentId: Optional[int] = None
    OpponentScore: Optional[float] = None
    OwnGoals: Optional[float] = None
    Passes: Optional[float] = None
    PassesCompleted: Optional[float] = None
    PenaltiesConceded: Optional[float] = None
    PenaltiesWon: Optional[float] = None
    PenaltyKickGoals: Optional[float] = None
    PenaltyKickMisses: Optional[float] = None
    PenaltyKickSaves: Optional[float] = None
    Possession: Optional[float] = None
    RedCards: Optional[float] = None
    RoundId: Optional[int] = None
    Score: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Shots: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    StatId: Optional[int] = None
    Tackles: Optional[float] = None
    TacklesWon: Optional[float] = None
    Team: Optional[str] = None
    TeamId: Optional[int] = None
    Touches: Optional[float] = None
    Updated: Optional[str] = None
    UpdatedUtc: Optional[str] = None
    YellowCards: Optional[float] = None
    YellowRedCards: Optional[float] = None


class TeamSeason(BaseModel):
    Assists: Optional[float] = None
    BlockedShots: Optional[float] = None
    CornersWon: Optional[float] = None
    Crosses: Optional[float] = None
    DefenderCleanSheets: Optional[float] = None
    FantasyPoints: Optional[float] = None
    FantasyPointsDraftKings: Optional[float] = None
    FantasyPointsFanDuel: Optional[float] = None
    FantasyPointsMondogoal: Optional[float] = None
    FantasyPointsYahoo: Optional[float] = None
    Fouled: Optional[float] = None
    Fouls: Optional[float] = None
    Games: Optional[int] = None
    GlobalTeamId: Optional[int] = None
    GoalkeeperCleanSheets: Optional[float] = None
    GoalkeeperGoalsAgainst: Optional[float] = None
    GoalkeeperSaves: Optional[float] = None
    GoalkeeperSingleGoalAgainst: Optional[float] = None
    GoalkeeperWins: Optional[float] = None
    Goals: Optional[float] = None
    Interceptions: Optional[float] = None
    LastManTackle: Optional[float] = None
    Minutes: Optional[float] = None
    Name: Optional[str] = None
    Offsides: Optional[float] = None
    OpponentScore: Optional[float] = None
    OwnGoals: Optional[float] = None
    Passes: Optional[float] = None
    PassesCompleted: Optional[float] = None
    PenaltiesConceded: Optional[float] = None
    PenaltiesWon: Optional[float] = None
    PenaltyKickGoals: Optional[float] = None
    PenaltyKickMisses: Optional[float] = None
    PenaltyKickSaves: Optional[float] = None
    Possession: Optional[float] = None
    RedCards: Optional[float] = None
    RoundId: Optional[int] = None
    Score: Optional[float] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Shots: Optional[float] = None
    ShotsOnGoal: Optional[float] = None
    StatId: Optional[int] = None
    Tackles: Optional[float] = None
    TacklesWon: Optional[float] = None
    Team: Optional[str] = None
    TeamId: Optional[int] = None
    Touches: Optional[float] = None
    Updated: Optional[str] = None
    UpdatedUtc: Optional[str] = None
    YellowCards: Optional[float] = None
    YellowRedCards: Optional[float] = None


class Venue(BaseModel):
    Address: Optional[str] = None
    Capacity: Optional[int] = None
    City: Optional[str] = None
    Country: Optional[str] = None
    GeoLat: Optional[float] = None
    GeoLong: Optional[float] = None
    Name: Optional[str] = None
    Nickname1: Optional[str] = None
    Nickname2: Optional[str] = None
    Open: Optional[bool] = None
    Opened: Optional[int] = None
    Surface: Optional[str] = None
    VenueId: Optional[int] = None
    Zip: Optional[str] = None


class FieldFormatActiveMembershipsGetResponse(RootModel[List[Membership]]):
    root: List[Membership]


class Format(Enum):
    xml = 'xml'
    json = 'json'


class Format10(Enum):
    json = 'json'
    xml = 'xml'


class Format11(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatHistoricalMembershipsGetResponse(RootModel[List[Membership]]):
    root: List[Membership]


class FieldFormatHistoricalMembershipsByCompetitionCompetitionGetResponse(
    RootModel[List[Membership]]
):
    root: List[Membership]


class FieldFormatHistoricalMembershipsByTeamTeamidGetResponse(
    RootModel[List[Membership]]
):
    root: List[Membership]


class FieldFormatMembershipsByCompetitionCompetitionGetResponse(
    RootModel[List[Membership]]
):
    root: List[Membership]


class FieldFormatMembershipsByTeamTeamidGetResponse(RootModel[List[Membership]]):
    root: List[Membership]


class FieldFormatPlayerGameStatsByDateDateGetResponse(RootModel[List[PlayerGame]]):
    root: List[PlayerGame]


class FieldFormatPlayerGameStatsByPlayerDatePlayeridGetResponse(
    RootModel[List[PlayerGame]]
):
    root: List[PlayerGame]


class FieldFormatPlayerSeasonStatsRoundidGetResponse(RootModel[List[PlayerSeason]]):
    root: List[PlayerSeason]


class FieldFormatPlayerSeasonStatsByPlayerRoundidPlayeridGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class FieldFormatPlayerSeasonStatsByTeamRoundidTeamGetResponse(
    RootModel[List[PlayerSeason]]
):
    root: List[PlayerSeason]


class FieldFormatPlayersGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatPlayersByTeamTeamidGetResponse(RootModel[List[Player]]):
    root: List[Player]


class FieldFormatRecentlyChangedMembershipsDaysGetResponse(RootModel[List[Membership]]):
    root: List[Membership]


class FieldFormatStandingsRoundidGetResponse(RootModel[List[Standing]]):
    root: List[Standing]


class FieldFormatTeamGameStatsByDateDateGetResponse(RootModel[List[TeamGame]]):
    root: List[TeamGame]


class FieldFormatTeamSeasonStatsRoundidGetResponse(RootModel[List[TeamSeason]]):
    root: List[TeamSeason]


class FieldFormatTeamsGetResponse(RootModel[List[Team]]):
    root: List[Team]


class Format32(Enum):
    json = 'json'
    xml = 'xml'


class Format33(Enum):
    xml = 'xml'
    json = 'json'


class FieldFormatVenuesGetResponse(RootModel[List[Venue]]):
    root: List[Venue]


class Game(BaseModel):
    Attendance: Optional[int] = None
    AwayTeamCountryCode: Optional[str] = None
    AwayTeamFormation: Optional[str] = None
    AwayTeamId: Optional[int] = None
    AwayTeamKey: Optional[str] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamName: Optional[str] = None
    AwayTeamPointSpreadPayout: Optional[int] = None
    AwayTeamScore: Optional[int] = None
    AwayTeamScoreExtraTime: Optional[int] = None
    AwayTeamScorePenalty: Optional[int] = None
    AwayTeamScorePeriod1: Optional[int] = None
    AwayTeamScorePeriod2: Optional[int] = None
    Clock: Optional[int] = None
    ClockDisplay: Optional[str] = None
    ClockExtra: Optional[int] = None
    DateTime: Optional[str] = None
    Day: Optional[str] = None
    DrawMoneyLine: Optional[int] = None
    GameId: Optional[int] = None
    GlobalAwayTeamId: Optional[int] = None
    GlobalGameId: Optional[int] = None
    GlobalHomeTeamId: Optional[int] = None
    Group: Optional[str] = None
    HomeTeamCountryCode: Optional[str] = None
    HomeTeamFormation: Optional[str] = None
    HomeTeamId: Optional[int] = None
    HomeTeamKey: Optional[str] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamName: Optional[str] = None
    HomeTeamPointSpreadPayout: Optional[int] = None
    HomeTeamScore: Optional[int] = None
    HomeTeamScoreExtraTime: Optional[int] = None
    HomeTeamScorePenalty: Optional[int] = None
    HomeTeamScorePeriod1: Optional[int] = None
    HomeTeamScorePeriod2: Optional[int] = None
    IsClosed: Optional[bool] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    Period: Optional[str] = None
    PlayoffAggregateScore_1: Optional[PlayoffAggregateScore] = Field(
        None, alias='PlayoffAggregateScore'
    )
    PointSpread: Optional[float] = None
    RoundId: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    Status: Optional[str] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None
    UpdatedUtc: Optional[str] = None
    VenueId: Optional[int] = None
    VenueType: Optional[str] = None
    Week: Optional[int] = None
    Winner: Optional[str] = None


class Round(BaseModel):
    CurrentRound: Optional[bool] = None
    CurrentWeek: Optional[int] = None
    EndDate: Optional[str] = None
    Games: Optional[List[Game]] = None
    Name: Optional[str] = None
    PlayerSeasons: Optional[List[PlayerSeason]] = None
    RoundId: Optional[int] = None
    Season: Optional[int] = None
    SeasonId: Optional[int] = None
    SeasonType: Optional[int] = None
    Standings: Optional[List[Standing]] = None
    StartDate: Optional[str] = None
    TeamSeasons: Optional[List[TeamSeason]] = None
    Type: Optional[str] = None


class Season(BaseModel):
    CompetitionId: Optional[int] = None
    CompetitionName: Optional[str] = None
    CurrentSeason: Optional[bool] = None
    EndDate: Optional[str] = None
    Name: Optional[str] = None
    Rounds: Optional[List[Round]] = None
    Season: Optional[int] = None
    SeasonId: Optional[int] = None
    StartDate: Optional[str] = None


class SeasonTeam(BaseModel):
    Active: Optional[bool] = None
    Gender: Optional[str] = None
    SeasonId: Optional[int] = None
    SeasonTeamId: Optional[int] = None
    Team_1: Optional[Team] = Field(None, alias='Team')
    TeamId: Optional[int] = None
    TeamName: Optional[str] = None
    Type: Optional[str] = None


class FieldFormatGamesByDateDateGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatScheduleRoundidGetResponse(RootModel[List[Game]]):
    root: List[Game]


class FieldFormatSeasonTeamsSeasonidGetResponse(RootModel[List[SeasonTeam]]):
    root: List[SeasonTeam]


class FieldFormatUpcomingScheduleByPlayerPlayeridGetResponse(RootModel[List[Game]]):
    root: List[Game]


class BoxScore(BaseModel):
    AdditionalAssistantReferee1: Optional[Referee] = None
    AdditionalAssistantReferee2: Optional[Referee] = None
    AssistantReferee1: Optional[Referee] = None
    AssistantReferee2: Optional[Referee] = None
    AwayTeamCoach: Optional[Coach] = None
    Bookings: Optional[List[Booking]] = None
    FourthReferee: Optional[Referee] = None
    Game_1: Optional[Game] = Field(None, alias='Game')
    Goals: Optional[List[Goal]] = None
    HomeTeamCoach: Optional[Coach] = None
    Lineups: Optional[List[Lineup]] = None
    MainReferee: Optional[Referee] = None
    PenaltyShootouts: Optional[List[PenaltyShootout]] = None
    PlayerGames: Optional[List[PlayerGame]] = None
    TeamGames: Optional[List[TeamGame]] = None
    VideoAssistantReferee: Optional[Referee] = None


class Competition(BaseModel):
    AreaId: Optional[int] = None
    AreaName: Optional[str] = None
    CompetitionId: Optional[int] = None
    Format: Optional[str] = None
    Gender: Optional[str] = None
    Key: Optional[str] = None
    Name: Optional[str] = None
    Seasons: Optional[List[Season]] = None
    Type: Optional[str] = None


class CompetitionDetail(BaseModel):
    AreaId: Optional[int] = None
    AreaName: Optional[str] = None
    CompetitionId: Optional[int] = None
    CurrentSeason: Optional[Season] = None
    Format: Optional[str] = None
    Games: Optional[List[Game]] = None
    Gender: Optional[str] = None
    Key: Optional[str] = None
    Name: Optional[str] = None
    Seasons: Optional[List[Season]] = None
    Teams: Optional[List[TeamDetail]] = None
    Type: Optional[str] = None


class DfsSlateGame(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    GameID: Optional[int] = None
    OperatorGameID: Optional[int] = None
    RemovedByOperator: Optional[bool] = None
    SlateGameID: Optional[int] = None
    SlateID: Optional[int] = None


class FieldFormatBoxScoresDateGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class FieldFormatBoxScoresByCompetitionCompetitionDateGetResponse(
    RootModel[List[BoxScore]]
):
    root: List[BoxScore]


class FieldFormatBoxScoresDeltaDateMinutesGetResponse(RootModel[List[BoxScore]]):
    root: List[BoxScore]


class FieldFormatBoxScoresDeltaByCompetitionCompetitionDateMinutesGetResponse(
    RootModel[List[BoxScore]]
):
    root: List[BoxScore]


class FieldFormatCompetitionsGetResponse(RootModel[List[Competition]]):
    root: List[Competition]


class Area(BaseModel):
    AreaId: Optional[int] = None
    Competitions: Optional[List[Competition]] = None
    CountryCode: Optional[str] = None
    Name: Optional[str] = None


class DfsSlate(BaseModel):
    CompetitionId: Optional[int] = None
    DfsSlateGames: Optional[List[DfsSlateGame]] = None
    DfsSlatePlayers: Optional[List[DfsSlatePlayer]] = None
    IsMultiDaySlate: Optional[bool] = None
    NumberOfGames: Optional[int] = None
    Operator: Optional[str] = None
    OperatorDay: Optional[str] = None
    OperatorGameType: Optional[str] = None
    OperatorName: Optional[str] = None
    OperatorSlateID: Optional[int] = None
    OperatorStartTime: Optional[str] = None
    RemovedByOperator: Optional[bool] = None
    SalaryCap: Optional[int] = None
    SlateID: Optional[int] = None
    SlateRosterSlots: Optional[List[str]] = None


class FieldFormatAreasGetResponse(RootModel[List[Area]]):
    root: List[Area]


class FieldFormatCompetitionHierarchyGetResponse(RootModel[List[Area]]):
    root: List[Area]


class FieldFormatDfsSlatesByDateDateGetResponse(RootModel[List[DfsSlate]]):
    root: List[DfsSlate]


class FieldFormatUpcomingDfsSlatesByCompetitionCompetitionIdGetResponse(
    RootModel[List[DfsSlate]]
):
    root: List[DfsSlate]
